title: 首页 # title of the blog used in <title> & as a logo
subtitle: /传递新知识 # subtitle of the blog used in <title> & next to name 
sass:
  sass_dir: _sass
  style: compact
plugins:
  - jekyll-postcss
  - jekyll-feed
  - jekyll-seo-tag
